const tempData = [
  {
    id: 1,
    title: "The Godfather",
    year: 1972,
    director: "Francis Ford Coppola",
    duration: "2h 55min",
    genre: ["Crime", "Drama"],
    rate: 9.2,
    poster: "https://i.postimg.cc/3RbYNHRp/the-godfather.webp",
  },
  {
    id: 2,
    title: "Natural born killers",
    year: 1994,
    director: "Oliver Stone",
    duration: "1h 59min",
    genre: ["Action", "Crime"],
    rate: 7.2,
    poster: "https://m.media-amazon.com/images/M/MV5BNGNjNjU1YmEtZGM5MC00ODgzLWEyY2MtZmZmNTlhOGU4OWJjXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg",
  },
  {
    id: 3,
    title: "Forrest Gump",
    year: 1994,
    director: "Robert Zemeckis",
    duration: "2h 22min",
    genre: ["Drama", "Romance"],
    rate: 8.8,
    poster: "https://i.postimg.cc/1tzyyz9s/forrest-gump.webp",
  },
  {
    id: 4,
    title: "Pulp fiction",
    year: 1994,
    director: "Quentin Tarantino",
    duration: "2h 34min",
    genre: ["Suspense", "Crime"],
    rate: 8.9,
    poster: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
  },
  {
    id: 5,
    title: "The Silence of the Lambs",
    year: 1991,
    director: "Jonathan Demme",
    duration: "1h 58min",
    genre: ["Crime", "Drama", "Thriller"],
    rate: 8.6,
    poster: "https://i.postimg.cc/3rV3H7zQ/the-silence-of-the-lambs.webp",
  },
  {
    id: 6,
    title: "The figth club",
    year: 1999,
    director: "David Fincher",
    duration: "2h 19min",
    genre: ["Suspense", "Action"],
    rate: 8.1,
    poster: "https://codigof.mx/wp-content/uploads/2018/08/ClubPeleaCF.jpg",
  },
  {
    id: 7,
    title: "The Matrix",
    year: 1999,
    director: "Lana Wachowski, Lilly Wachowski",
    duration: "2h 16min",
    genre: ["Action", "Sci-Fi"],
    rate: 8.7,
    poster: "https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg",
  },
  {
    id: 8,
    title: "Requiem for a dream",
    year: 2000,
    director: "Darren Aronofsky",
    duration: "1h 42min",
    genre: ["Terror", "Drama"],
    rate: 8.3,
    poster: "https://m.media-amazon.com/images/I/71-hosIpwkL._AC_UF894,1000_QL80_.jpg",
  },
  {
    id: 9,
    title: "Spider",
    year: 2002,
    director: "David Cronenberg",
    duration: "1h 38min",
    genre: ["Suspense", "Mystery"],
    rate: 6.8,
    poster: "https://m.media-amazon.com/images/M/MV5BMmY4OGRmNWMtNmIyNS00YWQ5LWJmMGUtMDI3MWRlMmQ0ZDQzL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
  },
  {
    id: 10,
    title: "The Dark Knight",
    year: 2008,
    director: "Christopher Nolan",
    duration: "2h 32min",
    genre: ["Action", "Crime", "Drama"],
    rate: 9.0,
    poster: "https://i.postimg.cc/yxMKhX08/the-dark-knight.webp",
  },
  {
    id: 11,
    title: "Avatar",
    year: 2009,
    director: "James Cameron",
    duration: "2h 42min",
    genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    rate: 7.8,
    poster: "https://i.postimg.cc/vTgM6SgK/avatar.webp",
  },
  {
    id: 12,
    title: "Inception",
    year: 2010,
    director: "Christopher Nolan",
    duration: "2h 28min",
    genre: ["Action", "Adventure", "Sci-Fi", "Thriller"],
    rate: 8.8,
    poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
  },
  {
    id: 13,
    title: "The Avengers",
    year: 2012,
    director: "Joss Whedon",
    duration: "2h 23min",
    genre: ["Action", "Adventure", "Sci-Fi"],
    rate: 8.0,
    poster: "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
  },
  {
    id: 14,
    title: "The Lord of the Rings",
    year: 2001,
    director: "Peter Jackson",
    duration: "2h 58min",
    genre: ["Action", "Adventure", "Drama", "Fantasy"],
    rate: 8.8,
    poster: "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
  },
  {
    id: 15,
    title: "Guardians of the Galaxy",
    year: 2017,
    director: "James Gunn",
    duration: "2h 16min",
    genre: ["Action", "Adventure", "Comedy"],
    rate: 7.7,
    poster: "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
  },
  {
    id: 16,
    title: "Interstellar",
    year: 2014,
    director: "Christopher Nolan",
    duration: "2h 49min",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    rate: 8.6,
    poster: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
  },
];

module.exports = tempData;
