module.exports = [
  {
    id: 101,
    pregunta: "¿Qué se entiende por frontend en el contexto de los proyectos full stack?",
    opciones: [
      "Es el pedazo de la aplicación que se enfoca en la interacción con los usuarios, presentación de información útil, definición de la visualización de datos y gestión de las interacciones de estos con la aplicación",
      "Es el componente responsable de gestionar la lógica de negocio y la interacción con la base de datos",
      "Es el servidor que aloja la parte visible de la aplicación",
      "Es el conjunto de herramientas utilizadas para controlar el acceso y la seguridad de la aplicación",
    ],
    respuestaCorrecta:
      "Es el pedazo de la aplicación que se enfoca en la interacción con los usuarios, presentación de información útil, definición de la visualización de datos y gestión de las interacciones de estos con la aplicación",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.01 Frontend",
  },
  {
    id: 102,
    pregunta: "¿Cuál es el rol del backend en una aplicación en el contexto de los proyectos full stack?",
    opciones: [
      "Es la parte encargada de la lógica de la aplicación y la gestión de bases de datos",
      "Es el componente responsable de la interacción directa con los usuarios y la presentación de la información",
      "Es el servidor que aloja la parte visible de la aplicación",
    ],
    respuestaCorrecta: "Es la parte encargada de la lógica de la aplicación y la gestión de bases de datos",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.02 Backend",
  },
  {
    id: 103,
    pregunta: "¿Cuál es la diferencia entre servidor y backend en el contexto de los proyectos full stack?",
    opciones: [
      "El servidor es una porción del backend que se encarga de operar solicitudes de un cliente, mientras que el backend es un conjunto de piezas como el servidor, base de datos, lógica de negocio, etc.",
      "El servidor es el conjunto de piezas que conforman el backend, incluyendo la lógica de negocio y la gestión de bases de datos",
      "El servidor y el backend son términos intercambiables que se refieren a la parte de la aplicación que se encarga de la interacción con los usuarios y la gestión de la información",
      "El servidor es la parte del frontend que se encarga de presentar la información al usuario, mientras que el backend es responsable de la lógica de la aplicación",
    ],
    respuestaCorrecta:
      "El servidor es una porción del backend que se encarga de operar solicitudes de un cliente, mientras que el backend es un conjunto de piezas como el servidor, base de datos, lógica de negocio, etc.",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.02 Backend",
  },
  {
    id: 104,
    pregunta: "¿Qué es un entorno de ejecución en el contexto del desarrollo de software?",
    opciones: [
      "Es el conjunto de herramientas y recursos utilizados para desarrollar y ejecutar aplicaciones de software",
      "Es el proceso de depuración y optimización de código en una aplicación",
      "Es el proceso de compilación de código fuente a código ejecutable",
    ],
    respuestaCorrecta: "Es el conjunto de herramientas y recursos utilizados para desarrollar y ejecutar aplicaciones de software",
    categoria: "Módulo 3: L1 Entorno de ejecución",
    seccion: "01.02 Backend",
  },
  {
    id: 105,
    pregunta: "¿Cuál es la función principal de un framework en el desarrollo de software?",
    opciones: [
      "Proporcionar una estructura y conjunto de herramientas predefinidas para facilitar el desarrollo de aplicaciones",
      "Optimizar y depurar el código de una aplicación para mejorar su rendimiento",
      "Interpretar y ejecutar el código de una aplicación en tiempo de ejecución",
      "Gestionar la interacción entre el usuario y la aplicación en una interfaz gráfica",
    ],
    respuestaCorrecta: "Proporcionar una estructura y conjunto de herramientas predefinidas para facilitar el desarrollo de aplicaciones",
    categoria: "Módulo 3: L2 Frameworks",
    seccion: "01.02 Backend",
  },
  {
    id: 106,
    pregunta: "¿Qué significa ODM y ORM en el contexto del desarrollo de software?",
    opciones: [
      "ODM se refiere a Object Data Mapping, mientras que ORM se refiere a Object-Relational Mapping",
      "ODM se refiere a Object-Relational Mapping, mientras que ORM se refiere a Object Data Mapping",
      "Ambos términos significan lo mismo y se utilizan indistintamente en el desarrollo de software",
      "ODM y ORM son lenguajes de programación especializados en el desarrollo de aplicaciones web",
    ],
    respuestaCorrecta: "ODM se refiere a Object Data Mapping, mientras que ORM se refiere a Object-Relational Mapping",
    categoria: "Módulo 3: L3 ODM/ORM",
    seccion: "01.02 Backend",
  },
  {
    id: 107,
    pregunta: "¿Qué es una API (Application Programming Interface) en el contexto de los proyectos full stack?",
    opciones: [
      "Define el conjunto de reglas y protocolos que permiten que dos sistemas se comuniquen entre sí, independientemente de las tecnologías utilizadas en cada uno de ellos",
      "Es un conjunto de herramientas utilizadas exclusivamente para el desarrollo del frontend de una aplicación",
      "Es el servidor que aloja la parte visible de la aplicación",
      "Es el componente responsable de la interacción directa con los usuarios y la presentación de la información",
    ],
    respuestaCorrecta:
      "Define el conjunto de reglas y protocolos que permiten que dos sistemas se comuniquen entre sí, independientemente de las tecnologías utilizadas en cada uno de ellos",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 108,
    pregunta: "¿Qué función desempeñan las APIs en la comunicación entre un cliente y un servidor?",
    opciones: [
      "Dictan cómo debe realizarse la solicitud de información de un cliente a un servidor, y cómo este deberá estructurar las respuestas",
      "Gestionan la presentación de la información al usuario final de la aplicación",
      "Controlan el acceso y la seguridad de la aplicación",
      "Realizan operaciones de procesamiento de datos en el servidor",
    ],
    respuestaCorrecta: "Dictan cómo debe realizarse la solicitud de información de un cliente a un servidor, y cómo este deberá estructurar las respuestas",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 109,
    pregunta: "¿Qué es el patrón RESTful (Representational State Transfer) en el contexto de diseño de API?",
    opciones: [
      "Es un estilo de arquitectura para diseñar una API basado en principios fundamentales de simplicidad y escalabilidad",
      "Es un protocolo de comunicación entre dispositivos en una red de computadoras",
      "Es una biblioteca de funciones utilizada para el desarrollo de aplicaciones web",
      "Es una herramienta de gestión de bases de datos relacionales",
    ],
    respuestaCorrecta: "Es un estilo de arquitectura para diseñar una API basado en principios fundamentales de simplicidad y escalabilidad",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 110,
    pregunta: "¿Qué se entiende por 'recurso' en el contexto del patrón RESTful?",
    opciones: [
      "Cualquier información que tenga sentido para el sistema, como un objeto, un servicio o incluso una entidad abstracta",
      "Una función utilizada para gestionar las solicitudes de los clientes en un servidor",
      "El nombre de dominio de un sitio web",
      "Un componente del frontend de una aplicación web",
    ],
    respuestaCorrecta: "Cualquier información que tenga sentido para el sistema, como un objeto, un servicio o incluso una entidad abstracta",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 111,
    pregunta: "¿Qué operaciones se definen en el contexto del sistema CRUD en el diseño de una API?",
    opciones: ["Crear, Leer, Actualizar, Eliminar", "Crear, Recordar, Modificar, Borrar", "Incluir, Obtener, mostrar, Borrar", "Insertar, Leer, Editar, actualizar"],
    respuestaCorrecta: "Crear, Leer, Actualizar, Eliminar",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 112,
    pregunta: "¿Cómo se representa y transfiere el estado de un recurso entre el cliente y el servidor en el contexto del patrón RESTful?",
    opciones: ["En algún formato de representación, comúnmente en JSON o XML", "Utilizando un lenguaje de marcado como HTML", "Mediante un formato binario"],
    respuestaCorrecta: "En algún formato de representación, comúnmente en JSON o XML",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 113,
    pregunta: "¿Qué función desempeñan los Identificadores Únicos (URI) en el contexto del patrón RESTful?",
    opciones: [
      "Proporcionan una forma de acceder y manipular un recurso específico",
      "Son utilizados exclusivamente para la autenticación de usuarios en una API",
      "Permiten la comunicación entre el cliente y el servidor mediante el protocolo HTTP",
      "Representan la estructura de una base de datos relacional",
    ],
    respuestaCorrecta: "Proporcionan una forma de acceder y manipular un recurso específico",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 114,
    pregunta: "¿Qué significa que la comunicación entre cliente y servidor sea 'sin estado' en el contexto del patrón RESTful?",
    opciones: [
      "Cada solicitud del cliente al servidor contiene toda la información necesaria para entender y procesar la solicitud, sin información de estado almacenada en el servidor entre las solicitudes",
      "El servidor almacena información de estado entre las solicitudes del cliente para mantener la coherencia de la sesión",
      "El servidor requiere que el cliente mantenga un estado de sesión para cada interacción",
      "La comunicación entre cliente y servidor no es posible en un entorno sin estado",
    ],
    respuestaCorrecta:
      "Cada solicitud del cliente al servidor contiene toda la información necesaria para entender y procesar la solicitud, sin información de estado almacenada en el servidor entre las solicitudes",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 118,
    pregunta: "¿Cuál es la principal diferencia entre una API y REST ?",
    opciones: [
      "Una API define un conjunto de reglas y protocolos para la comunicación entre sistemas, mientras que REST es un estilo arquitectónico que define cómo deben diseñarse las API para ser simples y escalables",
      "Una API es un estilo arquitectónico que define cómo deben diseñarse las API para ser simples y escalables, mientras que REST define un conjunto de reglas y protocolos para la comunicación entre sistemas",
      "API y REST son términos intercambiables y se refieren al mismo concepto en el contexto de la comunicación entre sistemas",
      "API y REST son dos protocolos diferentes utilizados para la comunicación entre sistemas, pero no tienen diferencias significativas",
    ],

    respuestaCorrecta:
      "Una API define un conjunto de reglas y protocolos para la comunicación entre sistemas, mientras que REST es un estilo arquitectónico que define cómo deben diseñarse las API para ser simples y escalables",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 119,
    pregunta: "¿Qué significa la palabra REST?",
    opciones: ["Representational State Transfer", "Real-time Server Transmission", "Resource Extraction and State Transmission", "Remote Entity Service Transfer"],
    respuestaCorrecta: "Representational State Transfer",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.03 API",
  },
  {
    id: 115,
    pregunta: "¿Qué función cumple un protocolo de red en el contexto de la comunicación entre computadoras?",
    opciones: [
      "Facilita la comunicación entre computadoras compartiendo recursos e información",
      "Controla el acceso a Internet de una computadora",
      "Administra los recursos de hardware de una computadora",
    ],
    respuestaCorrecta: "Facilita la comunicación entre computadoras compartiendo recursos e información",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
  {
    id: 116,
    pregunta: "¿Qué modelo permite organizar los protocolos de comunicación según su funcionalidad?",
    opciones: [
      "Modelo OSI (Open System Interconnection)",
      "Modelo TCP/IP (Transmission Control Protocol/Internet Protocol)",
      "Modelo FTP (File Transfer Protocol)",
      "Modelo HTTP (Hypertext Transfer Protocol)",
    ],
    respuestaCorrecta: "Modelo OSI (Open System Interconnection)",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
  {
    id: 117,
    pregunta: "¿Cuántas capas define el modelo OSI y cuál de ellas es responsable de la comunicación entre computadoras en una red?",
    opciones: [
      "Define siete capas, y la capa de Red (Network Layer) es responsable de la comunicación entre computadoras en una red",
      "Define cinco capas, y la capa de Transporte (Transport Layer) es responsable de la comunicación entre computadoras en una red",
      "Define nueve capas, y la capa de Enlace de Datos (Data Link Layer) es responsable de la comunicación entre computadoras en una red",
      "Define tres capas, y la capa de Aplicación (Application Layer) es responsable de la comunicación entre computadoras en una red",
    ],
    respuestaCorrecta: "Define siete capas, y la capa de Red (Network Layer) es responsable de la comunicación entre computadoras en una red",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
  {
    id: 120,
    pregunta: "¿Cuál es el significado de la sigla HTTP en el contexto de la comunicación en internet?",
    opciones: ["Hypertext Transfer Protocol", "Highway Transfer Protocol", "Home Transfer Protocol", "Hyperlink Transmission Protocol"],
    respuestaCorrecta: "Hypertext Transfer Protocol",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
  {
    id: 121,
    pregunta: "¿Qué permite el protocolo HTTP en el contexto de la comunicación en internet?",
    opciones: ["Transmisión de datos entre dispositivos conectados a la red", "Interconexión de dispositivos", "Codificación de datos", "Compresión de archivos"],
    respuestaCorrecta: "Transmisión de datos entre dispositivos conectados a la red",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
  {
    id: 122,
    pregunta: "¿Cómo se indica el tipo de solicitud que se desea realizar en el protocolo HTTP?",
    opciones: ["Mediante Métodos HTTP", "Mediante Status HTTP", "Mediante Protocolos HTTP", "Mediante Encabezados HTTP"],
    respuestaCorrecta: "Mediante Métodos HTTP",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
  {
    id: 123,
    pregunta: "¿Cuáles son los principales métodos utilizados en el protocolo HTTP?",
    opciones: ["GET, POST, PUT, DELETE", "SEARCH, CREATE, UPDATE, DELETE", "FETCH, SUBMIT, MODIFY, REMOVE", "REQUEST, RECEIVE, UPDATE, DELETE"],
    respuestaCorrecta: "GET, POST, PUT, DELETE",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
  {
    id: 124,
    pregunta: "¿Para qué se utiliza el método GET en el protocolo HTTP?",
    opciones: ["Para recuperar datos del servidor", "Para enviar datos al servidor", "Para actualizar datos en el servidor", "Para eliminar datos del servidor"],
    respuestaCorrecta: "Para recuperar datos del servidor",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
  {
    id: 125,
    pregunta: "¿Para qué se utiliza el método POST en el protocolo HTTP?",
    opciones: ["Para enviar datos al servidor", "Para recuperar datos del servidor", "Para actualizar datos en el servidor", "Para eliminar datos del servidor"],
    respuestaCorrecta: "Para enviar datos al servidor",
    categoria: "Módulo 2: L1 Proyecto Full Stack",
    seccion: "01.04 HTTP Protocol",
  },
];
// seccion: "01.04 HTTP Protocol",
