module.exports = [
  {
    id: 301,
    pregunta: "¿Qué es CSS (Cascading Style Sheets)?",
    opciones: [
      "El lenguaje que define la estructura y el contenido de las páginas web",
      "El lenguaje que define el aspecto y la presentación de las páginas web",
      "El lenguaje que define la interactividad y la funcionalidad de las páginas web",
      "El lenguaje que define la comunicación entre el cliente y el servidor en las páginas web",
    ],
    respuestaCorrecta: "El lenguaje que define el aspecto y la presentación de las páginas web",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "01 Frameworks CSS",
  },
  {
    id: 302,
    pregunta: "¿Qué solución nos ofrecen los frameworks CSS para crear estilos más complejos en una página web?",
    opciones: [
      "Facilitan la comunicación entre el cliente y el servidor",
      "Simplifican y agilizan el proceso de creación de estilos complejos",
      "Proporcionan herramientas para el desarrollo de funcionalidades interactivas",
      "Optimizan la gestión de bases de datos en la página web",
    ],
    respuestaCorrecta: "Simplifican y agilizan el proceso de creación de estilos complejos",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "01 Frameworks CSS",
  },
  {
    id: 303,
    pregunta: "¿Qué define un framework de CSS?",
    opciones: [
      "Un conjunto de reglas que indican cómo se deben estilizar los elementos HTML",
      "Una estructura que facilita el desarrollo de software relacionado con la presentación de una página web",
      "Un sistema de gestión de bases de datos específico para aplicaciones web",
      "Un protocolo de comunicación entre el cliente y el servidor para transferir datos en una página web",
    ],
    respuestaCorrecta: "Una estructura que facilita el desarrollo de software relacionado con la presentación de una página web",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "01 Frameworks CSS",
  },
  {
    id: 306,
    pregunta: "¿Cuál es una ventaja de utilizar frameworks de CSS?",
    opciones: [
      "Mayor complejidad en la escritura de código",
      "Menor flexibilidad en el diseño de la interfaz",
      "Disponibilidad de componentes reutilizables predefinidos",
      "Aumento en el tamaño de los archivos de estilo",
    ],
    respuestaCorrecta: "Disponibilidad de componentes reutilizables predefinidos",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "01 Frameworks CSS",
  },
  {
    id: 307,
    pregunta: "¿Qué función cumplen los sistemas de cuadrícula (grid systems) en los frameworks de CSS?",
    opciones: [
      "Crear diseños estáticos que no se adaptan a diferentes tamaños de pantalla",
      "Proporcionar una estructura flexible que se adapta a diferentes tamaños de pantalla",
      "Limitar la capacidad de personalización del diseño de la interfaz",
      "Incrementar la complejidad del código CSS",
    ],
    respuestaCorrecta: "Proporcionar una estructura flexible que se adapta a diferentes tamaños de pantalla",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "01 Frameworks CSS",
  },
  {
    id: 308,
    pregunta: "¿Qué función cumplen los estilos básicos para tipografía, colores e imágenes en los frameworks de CSS?",
    opciones: [
      "Proporcionar una apariencia estándar en todo el sitio y ahorrar tiempo en la configuración manual de estos estilos",
      "Limitar la personalización del diseño de la interfaz",
      "Incrementar la complejidad del código CSS",
      "Crear diseños estáticos que no se adaptan a diferentes tamaños de pantalla",
    ],
    respuestaCorrecta: "Proporcionar una apariencia estándar en todo el sitio y ahorrar tiempo en la configuración manual de estos estilos",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "01 Frameworks CSS",
  },
  {
    id: 309,
    pregunta: "¿Qué técnica utilizan muchos frameworks de CSS para garantizar la responsividad de los sitios web?",
    opciones: ["Clases específicas y medias queries", "Uso exclusivo de diseños fijos", "No se preocupan por la responsividad", "Dependencia total de JavaScript"],
    respuestaCorrecta: "Clases específicas y medias queries",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "01 Frameworks CSS",
  },
  {
    id: 310,
    pregunta: "¿Qué característica distingue a Bulma de otros frameworks de CSS?",
    opciones: ["Está basado en Flexbox", "Depende completamente de JavaScript", "Es difícil de personalizar", "No permite crear interfaces responsivas"],
    respuestaCorrecta: "Está basado en Flexbox",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "02 Frameworks más utilizados",
  },
  {
    id: 311,
    pregunta: "¿Qué característica distingue a Foundation de otros frameworks de CSS?",
    opciones: [
      "Utiliza un sistema de rejilla fijo",
      "Depende completamente de JavaScript",
      "Ofrece un conjunto de herramientas modular y personalizable",
      "Está diseñado solo para pequeños sitios web",
    ],
    respuestaCorrecta: "Ofrece un conjunto de herramientas modular y personalizable",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "02 Frameworks más utilizados",
  },
  {
    id: 312,
    pregunta: "¿Cuál es una característica destacada de Materialize como framework de CSS?",
    opciones: [
      "Diseñado exclusivamente para aplicaciones empresariales",
      "Ofrece una variedad de componentes y estilos modernos",
      "Depende en gran medida de JavaScript",
      "No permite la personalización de estilos",
    ],
    respuestaCorrecta: "Ofrece una variedad de componentes y estilos modernos",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "02 Frameworks más utilizados",
  },
  {
    id: 313,
    pregunta: "¿Cuál es una característica destacada de Tailwind CSS como framework de CSS?",
    opciones: [
      "Ofrece una gran cantidad de componentes predefinidos",
      "Depende en gran medida de JavaScript para su funcionamiento",
      "Adopta un enfoque orientado a clases para aplicar estilos",
      "Se enfoca exclusivamente en aplicaciones móviles",
    ],
    respuestaCorrecta: "Adopta un enfoque orientado a clases para aplicar estilos",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "02 Frameworks más utilizados",
  },
  {
    id: 314,
    pregunta: "¿Cuál es una desventaja de utilizar el framework Bulma para estilizar tablas?",
    opciones: [
      "Limitaciones en la personalización avanzada",
      "Fácil adaptación a diferentes tamaños de pantalla",
      "Curva de aprendizaje reducida",
      "Archivos pequeños y optimizados",
    ],
    respuestaCorrecta: "Limitaciones en la personalización avanzada",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "02 Frameworks más utilizados",
  },
  {
    id: 315,
    pregunta: "¿Cuál es una ventaja de utilizar el framework Foundation?",
    opciones: ["Es altamente personalizable", "Es altamente modular", "Facilidad de aprendizaje", "Curva de aprendizaje reducida"],
    respuestaCorrecta: "Es altamente personalizable",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "02 Frameworks más utilizados",
  },
  {
    id: 316,
    pregunta: "¿Cuál es una ventaja de utilizar el framework Tailwind CSS?",
    opciones: ["Es altamente personalizable y de bajo nivel", "Es altamente modular", "Facilidad de aprendizaje", "Curva de aprendizaje reducida"],
    respuestaCorrecta: "Es altamente personalizable y de bajo nivel",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "02 Frameworks más utilizados",
  },
  {
    id: 317,
    pregunta: "¿Cuál es una desventaja de utilizar el framework Materialize?",
    opciones: ["Diseño moderno y consistente", "Dependencia de JavaScript", "Facilidad de uso", "Flexibilidad y personalización"],
    respuestaCorrecta: "Dependencia de JavaScript",
    categoria: "Módulo 2: L3 Frameworks CSS",
    seccion: "02 Frameworks más utilizados",
  },
  {
    id: 318,
    pregunta: "¿Qué es Bootstrap?",
    opciones: ["Un lenguaje de programación", "Un framework para la creación de componentes responsivos", "Una base de datos", "Un servidor web"],
    respuestaCorrecta: "Un framework para la creación de componentes responsivos",
    seccion: "03 Bootstrap",
  },
  {
    id: 319,
    pregunta: "¿Quién desarrolló Bootstrap y cuál fue su origen?",
    opciones: [
      "Google, como un proyecto interno",
      "Microsoft, como parte de su suite de desarrollo",
      "Twitter, como proyecto interno",
      "Facebook, como parte de su plataforma de desarrollo",
    ],
    respuestaCorrecta: "Twitter, como proyecto interno",
    seccion: "03 Bootstrap",
  },
  {
    id: 320,
    pregunta: "¿Cuáles son algunas ventajas de usar Bootstrap?",
    opciones: [
      "Facilita la creación de componentes responsivos",
      "Ofrece una amplia variedad de componentes predefinidos",
      "Permite una rápida prototipación de proyectos",
      "Todas las anteriores",
    ],
    respuestaCorrecta: "Todas las anteriores",
    seccion: "03 Bootstrap",
  },
  {
    id: 321,
    pregunta: "¿Cuál es una forma sencilla de incorporar Bootstrap a una aplicación?",
    opciones: [
      "Incluyendo un enlace a los archivos CSS y JS de Bootstrap en el archivo HTML de la aplicación",
      "Descargando los archivos de Bootstrap y enlazándolos manualmente en la aplicación",
      "Usando un administrador de paquetes como npm o yarn para instalar Bootstrap",
      "Creando un CDN personalizado para Bootstrap e incluyéndolo en el archivo de configuración de la aplicación",
    ],
    respuestaCorrecta: "Incluyendo un enlace a los archivos CSS y JS de Bootstrap en el archivo HTML de la aplicación",
    seccion: "03 Bootstrap",
  },
  {
    id: 322,
    pregunta: "¿Cuál es la función principal de los contenedores en Bootstrap?",
    opciones: [
      "Envolver y alinear el contenido de la página web según el dispositivo en el que se visualiza",
      "Definir la estructura y diseño general de la página",
      "Estilizar los elementos de la página con clases predefinidas",
      "Gestionar la interacción del usuario en la página web",
    ],
    respuestaCorrecta: "Envolver y alinear el contenido de la página web según el dispositivo en el que se visualiza",
    seccion: "03.03 Bootstrap",
  },
  {
    id: 323,
    pregunta: "¿Cómo se puede incorporar un contenedor en Bootstrap?",
    opciones: [
      "Utilizando la clase container dentro de la etiqueta objetivo",
      "Utilizando la clase row dentro de la etiqueta objetivo",
      "Utilizando la clase col dentro de la etiqueta objetivo",
      "Utilizando la clase grid dentro de la etiqueta objetivo",
    ],
    respuestaCorrecta: "Utilizando la clase container dentro de la etiqueta objetivo",
    seccion: "03.03 Bootstrap",
  },
  {
    id: 324,
    pregunta: "¿Cuál es el propósito de las utilidades de texto en Bootstrap?",
    opciones: [
      "Ajustar el tamaño de letra, la alineación, el ancho y el estilo del texto",
      "Manejar la estructura y el diseño de la página web",
      "Agregar funcionalidades interactivas a la página web",
      "Optimizar el rendimiento del sitio web",
    ],
    respuestaCorrecta: "Ajustar el tamaño de letra, la alineación, el ancho y el estilo del texto",
    seccion: "03.03 Bootstrap",
  },
  {
    id: 325,
    pregunta: "¿Cómo se utilizan las listas en Bootstrap?",
    opciones: [
      "Definiendo el tag de lista padre con la clase list-group y marcando los elementos individuales con list-group-item",
      "Utilizando la clase list-container para agrupar los elementos de la lista",
      "Aplicando la clase list-item a cada elemento de la lista",
      "Agregando la clase list a los elementos de la lista y luego utilizando la clase list-item",
    ],
    respuestaCorrecta: "Definiendo el tag de lista padre con la clase list-group y marcando los elementos individuales con list-group-item",
    seccion: "03.03 Bootstrap",
  },
  {
    id: 326,
    pregunta: "¿Cómo se describe la presentación de múltiples elementos dentro de un recuadro con distribución uniforme en forma de tarjetas independientes en Bootstrap?",
    opciones: ["Cards & Grids", "Tarjetas Flexibles", "Contenedores de Tarjetas", "Grid-Card Layout"],
    respuestaCorrecta: "Cards & Grids",
    seccion: "03.03 Bootstrap",
  },
  {
    id: 327,
    pregunta: "¿Qué proporciona Bootstrap para agregar márgenes, padding o interlineado de forma sencilla?",
    opciones: ["Clases de Espaciado", "Utilidades de Diseño", "Componentes de Layout", "Estilos de Interfaz"],
    respuestaCorrecta: "Clases de Espaciado",
    seccion: "03.03 Bootstrap",
  },
  {
    id: 328,
    pregunta: "¿Cómo se utilizan las clases en Bootstrap para especificar el espaciado deseado, como margen o padding, en pixeles?",
    opciones: ["mt-3 y py-4", "espaciado-3 y relleno-4", "margen-top-3 y relleno-vertical-4", "clase-margen-3 y clase-relleno-4"],
    respuestaCorrecta: "mt-3 y py-4",
    seccion: "03.03 Bootstrap",
  },
];
// id: 318,
// seccion: "03 Bootstrap",
