// https://chat.openai.com/c/c36c9748-c820-4d6b-88f2-1e0c3733a5c4
// data_bootstrap.js

const preguntasBootstrap = [
  {
    id: 1,
    pregunta: "¿Qué es Bootstrap?",
    opciones: ["Un framework de front-end", "Un lenguaje de programación", "Un sistema de gestión de bases de datos", "Un protocolo de red"],
    respuestaCorrecta: "Un framework de front-end",
  },
  {
    id: 2,
    pregunta: "¿Quién desarrolló Bootstrap?",
    opciones: ["Google", "Facebook", "Twitter", "Bootstrap Corporation"],
    respuestaCorrecta: "Twitter",
  },
  {
    id: 3,
    pregunta: "¿Cuál es la versión actual de Bootstrap?",
    opciones: ["2", "3", "4", "5"],
    respuestaCorrecta: "5",
  },
  {
    id: 4,
    pregunta: "¿Qué lenguaje se utiliza principalmente en Bootstrap?",
    opciones: ["HTML", "JavaScript", "CSS", "PHP"],
    respuestaCorrecta: "HTML",
  },
  {
    id: 5,
    pregunta: "¿Cuál es la utilidad principal de Bootstrap?",
    opciones: ["Crear páginas web estáticas", "Crear aplicaciones móviles", "Diseñar interfaces de usuario responsivas", "Gestionar bases de datos"],
    respuestaCorrecta: "Diseñar interfaces de usuario responsivas",
  },
  {
    id: 6,
    pregunta: "¿Cuál es el componente principal de Bootstrap para crear diseños de cuadrícula?",
    opciones: ["Container", "Grid", "Row", "Column"],
    respuestaCorrecta: "Grid",
  },
  {
    id: 7,
    pregunta: "¿Qué CDN se puede utilizar para incluir Bootstrap en un proyecto?",
    opciones: ["Google CDN", "Facebook CDN", "Bootstrap CDN", "Twitter CDN"],
    respuestaCorrecta: "Bootstrap CDN",
  },
  {
    id: 8,
    pregunta: "¿Cuál es la clase de CSS que se utiliza para crear un botón en Bootstrap?",
    opciones: [".btn", ".button", ".btn-primary", ".btn-style"],
    respuestaCorrecta: ".btn",
  },
  {
    id: 9,
    pregunta: "¿Qué significa el acrónimo 'SCSS' en el contexto de Bootstrap?",
    opciones: ["Super CSS", "Simple CSS", "Sassy CSS", "Structured CSS"],
    respuestaCorrecta: "Sassy CSS",
  },
  {
    id: 10,
    pregunta: "¿Cuál es el nombre del sistema de diseño incluido en Bootstrap para ayudar en el diseño de aplicaciones web?",
    opciones: ["Material Design", "Flat Design", "Responsive Design", "Bootstrap Design"],
    respuestaCorrecta: "Material Design",
  },
  {
    id: 11,
    pregunta: "¿Qué componente de Bootstrap se utiliza para crear un menú desplegable?",
    opciones: ["Dropdown", "Navbar", "Collapse", "Menu"],
    respuestaCorrecta: "Dropdown",
  },
  {
    id: 12,
    pregunta: "¿Cuál es el sistema de rejilla (grid system) predeterminado de Bootstrap?",
    opciones: ["12 columnas", "16 columnas", "24 columnas", "8 columnas"],
    respuestaCorrecta: "12 columnas",
  },
  {
    id: 13,
    pregunta: "¿Qué clase se utiliza en Bootstrap para centrar un elemento horizontalmente?",
    opciones: [".center", ".middle", ".text-center", ".horizontal-center"],
    respuestaCorrecta: ".text-center",
  },
  {
    id: 14,
    pregunta: "¿Cuál es el nombre del sistema de rejilla (grid system) de Bootstrap que se adapta automáticamente al tamaño de la pantalla?",
    opciones: ["Fluid grid", "Responsive grid", "Auto grid", "Flexible grid"],
    respuestaCorrecta: "Fluid grid",
  },
  {
    id: 15,
    pregunta: "¿Cuál es la clase de Bootstrap utilizada para crear un formulario horizontal?",
    opciones: [".form-horizontal", ".form-inline", ".horizontal-form", ".form-horizontal-layout"],
    respuestaCorrecta: ".form-horizontal",
  },
  {
    id: 16,
    pregunta: "¿Qué componente de Bootstrap se utiliza para mostrar un conjunto de imágenes en una galería?",
    opciones: ["Gallery", "Carousel", "Slider", "Grid"],
    respuestaCorrecta: "Carousel",
  },
  {
    id: 17,
    pregunta: "¿Cuál es el prefijo utilizado para las clases de utilidad responsiva en Bootstrap?",
    opciones: ["lg-", "md-", "sm-", "xl-"],
    respuestaCorrecta: "sm-",
  },
  {
    id: 18,
    pregunta: "¿Qué clase se utiliza en Bootstrap para ocultar un elemento visualmente pero mantenerlo accesible para lectores de pantalla?",
    opciones: [".hidden", ".screen-reader-only", ".invisible", ".hide"],
    respuestaCorrecta: ".sr-only",
  },
  {
    id: 19,
    pregunta: "¿Cuál es el nombre del sistema de diseño incluido en Bootstrap para el diseño de formularios?",
    opciones: ["Bootstrap Forms", "Form Design", "Formly", "Form Grid"],
    respuestaCorrecta: "Formly",
  },
  {
    id: 20,
    pregunta: "¿Cómo se llama el conjunto de iconos predeterminado incluido en Bootstrap?",
    opciones: ["Font Awesome", "Bootstrap Icons", "Glyphicons", "Material Icons"],
    respuestaCorrecta: "Glyphicons",
  },
  {
    id: 21,
    pregunta: "¿Cuál es el nombre de la clase que se utiliza en Bootstrap para crear una barra de navegación responsiva que se colapsa en dispositivos móviles?",
    opciones: [".navbar-responsive", ".navbar-collapse", ".navbar-mobile", ".navbar-toggle"],
    respuestaCorrecta: ".navbar-toggle",
  },
  {
    id: 22,
    pregunta: "¿Qué método de JavaScript se utiliza para activar el componente de alerta de Bootstrap?",
    opciones: ["show()", "activate()", "alert()", "toggle()"],
    respuestaCorrecta: "alert()",
  },
  {
    id: 23,
    pregunta: "¿Qué clase se utiliza en Bootstrap para agregar márgenes automáticos a los lados izquierdo y derecho de un elemento?",
    opciones: [".margin-left-right-auto", ".mx-auto", ".margin-auto", ".auto-margin"],
    respuestaCorrecta: ".mx-auto",
  },
  {
    id: 24,
    pregunta: "¿Qué componente de Bootstrap se utiliza para crear una barra de progreso?",
    opciones: ["Progress", "Bar", "ProgressBar", "Progression"],
    respuestaCorrecta: "ProgressBar",
  },
  {
    id: 25,
    pregunta: "¿Cuál es el nombre del sistema de diseño incluido en Bootstrap para la alineación vertical de elementos?",
    opciones: ["Vertical Align", "VAlign", "Valign", "Flexbox"],
    respuestaCorrecta: "Flexbox",
  },
  {
    id: 26,
    pregunta: "¿Qué clase se utiliza en Bootstrap para hacer que un elemento sea visible solo en impresión?",
    opciones: [".visible-print", ".print-visible", ".print-only", ".visible-on-print"],
    respuestaCorrecta: ".visible-print",
  },
  {
    id: 27,
    pregunta: "¿Cómo se llama el componente de Bootstrap que permite crear modales?",
    opciones: ["Dialog", "Popup", "Modal", "Window"],
    respuestaCorrecta: "Modal",
  },
  {
    id: 28,
    pregunta: "¿Qué clase se utiliza en Bootstrap para cambiar el color del texto a blanco?",
    opciones: [".text-light", ".text-white", ".text-bright", ".text-blank"],
    respuestaCorrecta: ".text-white",
  },
  {
    id: 29,
    pregunta: "¿Cuál es el nombre del complemento de JavaScript de Bootstrap que se utiliza para crear carruseles de imágenes?",
    opciones: ["Carousel.js", "Slider.js", "Slideshow.js", "Carousel"],
    respuestaCorrecta: "Carousel",
  },
  {
    id: 30,
    pregunta: "¿Qué clase se utiliza en Bootstrap para hacer que un elemento desaparezca visualmente pero siga ocupando espacio en el diseño?",
    opciones: [".invisible", ".hide", ".hidden", ".vanish"],
    respuestaCorrecta: ".invisible",
  },
  {
    id: 31,
    pregunta: "¿Qué clase se utiliza en Bootstrap para crear un jumbotron?",
    opciones: [".jumbotron", ".hero", ".big-box", ".banner"],
    respuestaCorrecta: ".jumbotron",
  },
  {
    id: 32,
    pregunta: "¿Cuál es el nombre del sistema de diseño incluido en Bootstrap para la alineación horizontal de elementos?",
    opciones: ["Horizontal Align", "HAlign", "Halign", "Flexbox"],
    respuestaCorrecta: "Flexbox",
  },
  {
    id: 33,
    pregunta: "¿Qué clase se utiliza en Bootstrap para crear una lista ordenada con estilos de Bootstrap?",
    opciones: [".list-group", ".ordered-list", ".ordered-group", ".list"],
    respuestaCorrecta: ".list-group",
  },
  {
    id: 34,
    pregunta: "¿Cuál es el prefijo utilizado para las clases de tamaño de pantalla extra grande en Bootstrap?",
    opciones: ["xl-", "lg-", "md-", "sm-"],
    respuestaCorrecta: "xl-",
  },
  {
    id: 35,
    pregunta: "¿Qué clase se utiliza en Bootstrap para hacer que un elemento flote a la derecha?",
    opciones: [".float-right", ".right-float", ".right", ".pull-right"],
    respuestaCorrecta: ".float-right",
  },
  {
    id: 36,
    pregunta: "¿Cuál es el nombre de la clase que se utiliza en Bootstrap para crear una barra de navegación vertical?",
    opciones: [".navbar-vertical", ".nav-vertical", ".vertical-nav", ".sidebar"],
    respuestaCorrecta: ".sidebar",
  },
  {
    id: 37,
    pregunta: "¿Qué clase se utiliza en Bootstrap para crear un grupo de botones?",
    opciones: [".btn-group", ".button-group", ".group-btn", ".button-set"],
    respuestaCorrecta: ".btn-group",
  },
  {
    id: 38,
    pregunta: "¿Cuál es el nombre del complemento de JavaScript de Bootstrap que se utiliza para crear pestañas?",
    opciones: ["Tabs.js", "Tabify.js", "Tab.js", "Tabulator.js"],
    respuestaCorrecta: "Tab.js",
  },
  {
    id: 39,
    pregunta: "¿Qué clase se utiliza en Bootstrap para agregar un borde redondeado a un elemento?",
    opciones: [".rounded", ".border-rounded", ".round-border", ".border-round"],
    respuestaCorrecta: ".rounded",
  },
  {
    id: 40,
    pregunta: "¿Cuál es el nombre del sistema de diseño incluido en Bootstrap para la organización de contenido en tarjetas?",
    opciones: ["Card Layout", "Card Grid", "Card System", "Card Deck"],
    respuestaCorrecta: "Card Deck",
  },
  {
    id: 41,
    pregunta: "¿Qué clase se utiliza en Bootstrap para crear un encabezado de página?",
    opciones: [".header", ".page-header", ".top-header", ".page-top"],
    respuestaCorrecta: ".page-header",
  },
  {
    id: 42,
    pregunta: "¿Cuál es el nombre del complemento de JavaScript de Bootstrap que se utiliza para crear alertas emergentes?",
    opciones: ["Alertify.js", "Alert.js", "Toastr.js", "Alert.js"],
    respuestaCorrecta: "Alert.js",
  },
  {
    id: 43,
    pregunta: "¿Qué clase se utiliza en Bootstrap para crear un grupo de pestañas?",
    opciones: [".nav-tabs", ".tab-group", ".tabs", ".tab-set"],
    respuestaCorrecta: ".nav-tabs",
  },
  {
    id: 44,
    pregunta: "¿Cuál es el nombre del complemento de JavaScript de Bootstrap que se utiliza para crear menús desplegables?",
    opciones: ["Dropdown.js", "Menu.js", "Popper.js", "Select.js"],
    respuestaCorrecta: "Dropdown.js",
  },
  {
    id: 45,
    pregunta: "¿Qué clase se utiliza en Bootstrap para crear un grupo de botones de navegación?",
    opciones: [".nav", ".nav-group", ".nav-bar", ".navbar"],
    respuestaCorrecta: ".navbar",
  },
  {
    id: 46,
    pregunta: "¿Cuál es el nombre del sistema de diseño incluido en Bootstrap para la creación de tablas?",
    opciones: ["Table Layout", "Table System", "Table Grid", "Table Design"],
    respuestaCorrecta: "Table Layout",
  },
  {
    id: 47,
    pregunta: "¿Qué clase se utiliza en Bootstrap para crear un carrusel de imágenes?",
    opciones: [".slider", ".carousel", ".image-carousel", ".image-slider"],
    respuestaCorrecta: ".carousel",
  },
  {
    id: 48,
    pregunta: "¿Cuál es el nombre del complemento de JavaScript de Bootstrap que se utiliza para crear tooltips?",
    opciones: ["Tooltip.js", "Popper.js", "Tipper.js", "Hint.js"],
    respuestaCorrecta: "Tooltip.js",
  },
  {
    id: 49,
    pregunta: "¿Qué clase se utiliza en Bootstrap para crear un grupo de píldoras (pills)?",
    opciones: [".nav-pills", ".pill-group", ".pill-nav", ".nav-group"],
    respuestaCorrecta: ".nav-pills",
  },
  {
    id: 50,
    pregunta: "¿Cuál es el nombre del sistema de diseño incluido en Bootstrap para la creación de listas de elementos?",
    opciones: ["List Layout", "List System", "List Grid", "List Group"],
    respuestaCorrecta: "List Group",
  },
];

module.exports = preguntasBootstrap;
