// data.js

module.exports = [
  {
    id: 1,
    pregunta: "¿Qué es HTTP?",
    opciones: [
      "El lenguaje que permite a los navegadores y servidores compartir información a través de internet",
      "Un lenguaje de programación para crear páginas web dinámicas",
      "Una base de datos relacional ampliamente utilizada en la web",
      "Un protocolo de comunicación entre dispositivos Bluetooth",
    ],
    respuestaCorrecta: "El lenguaje que permite a los navegadores y servidores compartir información a través de internet",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidors",
  },
  {
    id: 2,
    pregunta: "¿Qué representa el 'localhost' y el puerto en el contexto de las aplicaciones web?",
    opciones: [
      "El 'localhost' indica la dirección IP del servidor y el puerto especifica la aplicación en particular",
      "El 'localhost' es el nombre de dominio de un servidor y el puerto es la dirección física del mismo",
      "El 'localhost' es la dirección del cliente y el puerto indica la dirección del servidor",
      "El 'localhost' es la dirección del servidor y el puerto especifica la puerta de entrada a una aplicación en ese servidor",
    ],
    respuestaCorrecta: "El 'localhost' es la dirección del servidor y el puerto especifica la puerta de entrada a una aplicación en ese servidor",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidor",
  },
  {
    id: 3,
    pregunta: "¿Cuál es la analogía propuesta para entender el funcionamiento de los controladores en un servidor web?",
    opciones: [
      "El chef en acción en una cocina, recibiendo pedidos y preparando platos",
      "El mecánico reparando un automóvil en un taller",
      "El capitán de un barco dirigiendo la nave en alta mar",
      "El conductor de un autobús llevando pasajeros a su destino",
    ],
    respuestaCorrecta: "El chef en acción en una cocina, recibiendo pedidos y preparando platos",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidor",
  },
  {
    id: 4,
    pregunta: "¿Cómo se comparan los servicios en un servidor web con el personal en un restaurante?",
    opciones: [
      "Los servicios son como un equipo coordinado de meseros, cada uno especializado en un área particular",
      "Los servicios son como el chef en la cocina, preparando los platos según los pedidos",
      "Los servicios son como los clientes en el restaurante, solicitando diferentes platos",
      "Los servicios son como los ingredientes en la despensa, utilizados para preparar los platos",
    ],
    respuestaCorrecta: "Los servicios son como un equipo coordinado de meseros, cada uno especializado en un área particular",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidor",
  },
  {
    id: 5,
    pregunta: "¿Cuál es la función de los middlewares en un servidor web?",
    opciones: [
      "Mejorar o darle un toque final al resultado antes de que sea enviado al cliente",
      "Encargarse de recibir y procesar las solicitudes de los clientes",
      "Gestionar la autenticación y autorización de usuarios",
      "Interactuar con la base de datos para recuperar o almacenar información",
    ],
    respuestaCorrecta: "Mejorar o darle un toque final al resultado antes de que sea enviado al cliente",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidor",
  },
  {
    id: 6,
    pregunta: "¿Cuál es el propósito principal del scaffolding de proyecto en el desarrollo web?",
    opciones: [
      "Crear una estructura de carpetas para organizar el código de manera eficiente",
      "Ejecutar pruebas automáticas en el código",
      "Optimizar el rendimiento del servidor",
      "Implementar funciones de seguridad en el proyecto",
    ],
    respuestaCorrecta: "Crear una estructura de carpetas para organizar el código de manera eficiente",
    categoria: "Modulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 7,
    pregunta: "¿Cuáles son las carpetas comúnmente utilizadas en el contexto de desarrollo web y patrones de diseño MVC para organizar y estructurar el código?",
    opciones: ["Rutas y Controladores", "Vistas y Modelos", "Clientes y Servidores", "CSS y JS"],
    respuestaCorrecta: "Rutas y Controladores",
    categoria: "Modulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 8,
    pregunta: "¿Qué término se refiere a los archivos que definen los endpoints de la API y los métodos HTTP?",
    opciones: ["Ruta", "Servicio", "Controlador"],
    respuestaCorrecta: "Ruta",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 9,
    pregunta: "¿Qué término se refiere a los módulos que encapsulan la lógica de negocio e interactúan directamente con la base de datos?",
    opciones: ["Servicio", "Ruta", "Controladores"],
    respuestaCorrecta: "Servicio",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 10,
    pregunta: "¿Qué término se refiere a los archivos que procesan las solicitudes y dan una respuesta al cliente?",
    opciones: ["Controladores", "Servicio", "Ruta"],
    respuestaCorrecta: "Controladores",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 11,
    pregunta: "¿Cómo se organiza un proyecto utilizando el enfoque funcional?",
    opciones: [
      "Por características específicas del proyecto, como 'usuarios', 'publicaciones', etc.",
      "Por la estructura del servidor y la base de datos",
      "Por la fecha de creación de los archivos",
      "Por la prioridad de las tareas a realizar",
    ],
    respuestaCorrecta: "Por características específicas del proyecto, como 'usuarios', 'publicaciones', etc.",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 12,
    pregunta: "¿Cómo se organiza un proyecto utilizando el enfoque modular?",
    opciones: [
      "En carpetas que representan roles o componentes clave, como 'rutas', 'controladores' y 'servicios'",
      "Por características específicas del proyecto, como 'usuarios', 'publicaciones', etc.",
      "Por la estructura del servidor y la base de datos",
      "Por la fecha de creación de los archivos",
    ],
    respuestaCorrecta: "En carpetas que representan roles o componentes clave, como 'rutas', 'controladores' y 'servicios'",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 13,
    pregunta: "¿Cuál es la función del método listen en Express?",
    opciones: [
      "Iniciar un servidor para que escuche las solicitudes HTTP en un puerto específico",
      "Definir las rutas de la aplicación web",
      "Realizar operaciones de autenticación de usuarios",
      "Gestionar las solicitudes de base de datos",
    ],
    respuestaCorrecta: "Iniciar un servidor para que escuche las solicitudes HTTP en un puerto específico",
    categoria: "Módulo 2: L-07 Express",
    seccion: "03 Creación de servidor",
  },
  {
    id: 14,
    pregunta: "¿Cuál es la utilidad del callback en el método listen de Express?",
    opciones: [
      "Realizar acciones específicas después de que el servidor se ha iniciado correctamente",
      "Definir las rutas de la aplicación web",
      "Realizar operaciones de autenticación de usuarios",
      "Gestionar las solicitudes de base de datos",
    ],
    respuestaCorrecta: "Realizar acciones específicas después de que el servidor se ha iniciado correctamente",
    categoria: "Módulo 2: L-07 Express",
    seccion: "03 Creación de servidor",
  },
  {
    id: 15,
    pregunta: "¿Qué función cumplen los controladores en el contexto de desarrollo web?",
    opciones: [
      "Manejar las solicitudes HTTP, llevando a cabo la lógica necesaria y enviando una respuesta al cliente",
      "Gestionar la interacción con la base de datos",
      "Definir la estructura y el estilo de la página web",
      "Controlar el acceso de los usuarios a las diferentes partes de la aplicación",
    ],
    respuestaCorrecta: "Manejar las solicitudes HTTP, llevando a cabo la lógica necesaria y enviando una respuesta al cliente",
    categoria: "Módulo 2: L-07 Express",
    seccion: "04 Controladores",
  },
  {
    id: 16,
    pregunta: "¿Cuál es el propósito principal del enrutado en Express?",
    opciones: [
      "Gestionar las rutas de la aplicación y dirigir las solicitudes hacia controladores específicos",
      "Definir la estructura y el estilo de la página web",
      "Controlar el acceso de los usuarios a las diferentes partes de la aplicación",
      "Realizar operaciones de autenticación de usuarios",
    ],
    respuestaCorrecta: "Gestionar las rutas de la aplicación y dirigir las solicitudes hacia controladores específicos",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
  {
    id: 17,
    pregunta: "¿Qué método se utiliza para crear un enrutador en Express?",
    codigo: {
      lag: "javascript",
      snippet: "// Enrutador de Usuarios\nconst enrutadorUsuarios = ",
    },
    opciones: ["express.Router()", "express.Server()", "express.Application()", "express.Middleware()"],
    respuestaCorrecta: "express.Router()",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
  {
    id: 18,
    pregunta: "¿Qué se asocia con un método HTTP y uno de los métodos del controlador correspondiente en Express?",
    codigo: {
      lag: "javascript",
      snippet: '// Rutas para Usuarios\nenrutadorUsuarios.get("/", controladorUsuarios.obtenerUsuarios)\nenrutadorUsuarios.post("/", controladorUsuarios.crearUsuario)',
    },
    opciones: ["Rutas", "Controladores", "Enrutadores", "Middleware"],
    respuestaCorrecta: "Rutas",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
  {
    id: 19,
    pregunta: "¿Qué sucede al incorporar un enrutador de Usuarios en el enrutador principal de la aplicación en Express?",
    codigo: {
      lag: "javascript",
      snippet: '// Enrutador principal \nconst enrutadorPrincipal = express.Router()\n\n//Uso del enrutador de Usuarios\nenrutadorPrincipal.use("/usuarios", enrutadorUsuarios)',
    },
    opciones: [
      "Todas las solicitudes dirigidas a '/usuarios' serán manejadas por el enrutador de usuarios",
      "Las solicitudes a '/usuarios' serán redirigidas al enrutador principal de la aplicación",
      "Se eliminarán todas las solicitudes dirigidas a '/usuarios'",
    ],
    respuestaCorrecta: "Todas las solicitudes dirigidas a '/usuarios' serán manejadas por el enrutador de usuarios",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
  {
    id: 20,
    pregunta: "¿Qué función tiene <br>router.use('/usuarios', usuariosRouter) <br>en Express?",
    codigo: {
      lag: "javascript",
      snippet:
        '// Enrutador de usuarios.js\nconst express = require("express")\nconst router = express.Router()\n\nrouter.get("/",(req, res)=>{\n    res.send("Módulo de Usuarios")\n})\n\nmodule.exports = router\n\n// Enrutador index.js\nconst express = require("express")\nconst router = express.Router()\n\nconst usuariosRouter = require("./usarios")\n\nrouter.use("./usuarios", usuariosRouter)\n\nmodule.exports = router',
    },
    opciones: [
      "Indicar que todas las solicitudes que comienzan con '/usuarios' deben ser dirigidas al enrutador de usuarios",
      "Especificar el punto de entrada principal de la aplicación",
      "Crear un nuevo enrutador llamado 'usuariosRouter'",
    ],
    respuestaCorrecta: "Indicar que todas las solicitudes que comienzan con '/usuarios' deben ser dirigidas al enrutador de usuarios",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
  {
    id: 21,
    pregunta: "¿Cuál es el propósito principal de los enrutadores index en Express?",
    opciones: [
      "Actuar como puntos de entrada principales para diferentes secciones de una aplicación",
      "Definir rutas específicas para cada sección de la aplicación",
      "Organizar las rutas en una estructura jerárquica",
    ],
    respuestaCorrecta: "Actuar como puntos de entrada principales para diferentes secciones de una aplicación",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
  {
    id: 22,
    pregunta: "En Express, ¿cuál es el propósito de los objetos 'req' y 'res' en la función de un controlador?",
    opciones: [
      "Representan el objeto de solicitud (request) y el objeto de respuesta (response) respectivamente, permitiendo al controlador interactuar con los datos de la solicitud y enviar una respuesta al cliente",
      "Representan el objeto de respuesta (response) y el objeto de solicitud (request) respectivamente, permitiendo al controlador interactuar con los datos de la respuesta y enviar una solicitud al cliente",
      "Son utilizados únicamente para autenticación y autorización de usuarios en la aplicación",

      "Actúan como variables locales dentro de la función del controlador para almacenar datos temporales durante la ejecución del código",
    ],
    respuestaCorrecta:
      "Representan el objeto de solicitud (request) y el objeto de respuesta (response) respectivamente, permitiendo al controlador interactuar con los datos de la solicitud y enviar una respuesta al cliente",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
  {
    id: 23,
    pregunta: "¿Cuál es la función principal del método de respuesta 'send()' en Express?",
    codigo: {
      lag: "javascript",
      snippet: 'router.get("/",(req, res)=>{\n    res.send("Hello World")\n})',
    },
    opciones: [
      "Enviar una respuesta al cliente, que puede ser un objeto, una cadena de texto o un archivo",
      "Recibir y procesar datos de un formulario HTML",
      "Definir las rutas de la aplicación web",
      "Establecer la configuración del servidor Express",
    ],
    respuestaCorrecta: "Enviar una respuesta al cliente, que puede ser un objeto, una cadena de texto o un archivo",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },

  {
    id: 24,
    pregunta: "¿Qué función cumplen los métodos HTTP en Express?",
    codigo: {
      lag: "javascript",
      snippet:
        "// Ruta y método GET\napp.get('/', (req, res) => {\n  res.send('Hola, mundo!');\n});\n\n// Ruta y método POST\napp.post('/usuarios', (req, res) => {\n  res.send('Usuario creado');\n});",
    },
    opciones: [
      "Definir la acción que se realizará en una solicitud específica",
      "Gestionar la autenticación de usuarios en la aplicación",
      "Controlar el acceso de los usuarios a las diferentes partes de la aplicación",
      "Establecer la configuración del servidor Express",
    ],
    respuestaCorrecta: "Definir la acción que se realizará en una solicitud específica",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
  {
    id: 25,
    pregunta: "¿Cuál es el propósito principal de los enrutadores por entidad en Express?",
    codigo: {
      lag: "javascript",
      snippet: 'router.use("/users", userRouter);\nrouter.use("/posts", postRouter);',
    },
    opciones: [
      "Gestionar rutas relacionadas con una entidad específica, como Usuarios o Productos",
      "Controlar el acceso de los usuarios a las diferentes partes de la aplicación",
      "Establecer la configuración global del servidor Express",
    ],
    respuestaCorrecta: "Gestionar rutas relacionadas con una entidad específica, como Usuarios o Productos",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
];
