// data.js

module.exports = [
  {
    id: 1,
    pregunta: "¿Qué es HTTP?",
    opciones: [
      "El lenguaje que permite a los navegadores y servidores compartir información a través de internet",
      "Un lenguaje de programación para crear páginas web dinámicas",
      "Una base de datos relacional ampliamente utilizada en la web",
      "Un protocolo de comunicación entre dispositivos Bluetooth",
    ],
    respuestaCorrecta: "El lenguaje que permite a los navegadores y servidores compartir información a través de internet",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidors",
  },
  {
    id: 2,
    pregunta: "¿Qué representa el 'localhost' y el puerto en el contexto de las aplicaciones web?",
    opciones: [
      "El 'localhost' indica la dirección IP del servidor y el puerto especifica la aplicación en particular",
      "El 'localhost' es el nombre de dominio de un servidor y el puerto es la dirección física del mismo",
      "El 'localhost' es la dirección del cliente y el puerto indica la dirección del servidor",
      "El 'localhost' es la dirección del servidor y el puerto especifica la puerta de entrada a una aplicación en ese servidor",
    ],
    respuestaCorrecta: "El 'localhost' es la dirección del servidor y el puerto especifica la puerta de entrada a una aplicación en ese servidor",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidor",
  },
  {
    id: 3,
    pregunta: "¿Cuál es la analogía propuesta para entender el funcionamiento de los controladores en un servidor web?",
    opciones: [
      "El chef en acción en una cocina, recibiendo pedidos y preparando platos",
      "El mecánico reparando un automóvil en un taller",
      "El capitán de un barco dirigiendo la nave en alta mar",
      "El conductor de un autobús llevando pasajeros a su destino",
    ],
    respuestaCorrecta: "El chef en acción en una cocina, recibiendo pedidos y preparando platos",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidor",
  },
  {
    id: 4,
    pregunta: "¿Cómo se comparan los servicios en un servidor web con el personal en un restaurante?",
    opciones: [
      "Los servicios son como un equipo coordinado de meseros, cada uno especializado en un área particular",
      "Los servicios son como el chef en la cocina, preparando los platos según los pedidos",
      "Los servicios son como los clientes en el restaurante, solicitando diferentes platos",
      "Los servicios son como los ingredientes en la despensa, utilizados para preparar los platos",
    ],
    respuestaCorrecta: "Los servicios son como un equipo coordinado de meseros, cada uno especializado en un área particular",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidor",
  },
  {
    id: 5,
    pregunta: "¿Cuál es la función de los middlewares en un servidor web?",
    opciones: [
      "Mejorar o darle un toque final al resultado antes de que sea enviado al cliente",
      "Encargarse de recibir y procesar las solicitudes de los clientes",
      "Gestionar la autenticación y autorización de usuarios",
      "Interactuar con la base de datos para recuperar o almacenar información",
    ],
    respuestaCorrecta: "Mejorar o darle un toque final al resultado antes de que sea enviado al cliente",
    categoria: "Modulo 2: L-07 Express",
    seccion: "01 Estructura básica del servidor",
  },
  {
    id: 6,
    pregunta: "¿Cuál es el propósito principal del scaffolding de proyecto en el desarrollo web?",
    opciones: [
      "Crear una estructura de carpetas para organizar el código de manera eficiente",
      "Ejecutar pruebas automáticas en el código",
      "Optimizar el rendimiento del servidor",
      "Implementar funciones de seguridad en el proyecto",
    ],
    respuestaCorrecta: "Crear una estructura de carpetas para organizar el código de manera eficiente",
    categoria: "Modulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 7,
    pregunta: "¿Cuáles son las carpetas comúnmente utilizadas en el contexto de desarrollo web y patrones de diseño MVC para organizar y estructurar el código?",
    opciones: ["Rutas y Controladores", "Vistas y Modelos", "Clientes y Servidores", "CSS y JS"],
    respuestaCorrecta: "Rutas y Controladores",
    categoria: "Modulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 8,
    pregunta: "¿Qué término se refiere a los archivos que definen los endpoints de la API y los métodos HTTP?",
    opciones: ["Ruta", "Servicio", "Controlador"],
    respuestaCorrecta: "Ruta",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 9,
    pregunta: "¿Qué término se refiere a los módulos que encapsulan la lógica de negocio e interactúan directamente con la base de datos?",
    opciones: ["Servicio", "Ruta", "Controladores"],
    respuestaCorrecta: "Servicio",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 10,
    pregunta: "¿Qué término se refiere a los archivos que procesan las solicitudes y dan una respuesta al cliente?",
    opciones: ["Controladores", "Servicio", "Ruta"],
    respuestaCorrecta: "Controladores",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 11,
    pregunta: "¿Cómo se organiza un proyecto utilizando el enfoque funcional?",
    opciones: [
      "Por características específicas del proyecto, como 'usuarios', 'publicaciones', etc.",
      "Por la estructura del servidor y la base de datos",
      "Por la fecha de creación de los archivos",
      "Por la prioridad de las tareas a realizar",
    ],
    respuestaCorrecta: "Por características específicas del proyecto, como 'usuarios', 'publicaciones', etc.",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 12,
    pregunta: "¿Cómo se organiza un proyecto utilizando el enfoque modular?",
    opciones: [
      "En carpetas que representan roles o componentes clave, como 'rutas', 'controladores' y 'servicios'",
      "Por características específicas del proyecto, como 'usuarios', 'publicaciones', etc.",
      "Por la estructura del servidor y la base de datos",
      "Por la fecha de creación de los archivos",
    ],
    respuestaCorrecta: "En carpetas que representan roles o componentes clave, como 'rutas', 'controladores' y 'servicios'",
    categoria: "Módulo 2: L-07 Express",
    seccion: "02 Scaffolding de proyecto",
  },
  {
    id: 13,
    pregunta: "¿Cuál es la función del método listen en Express?",
    opciones: [
      "Iniciar un servidor para que escuche las solicitudes HTTP en un puerto específico",
      "Definir las rutas de la aplicación web",
      "Realizar operaciones de autenticación de usuarios",
      "Gestionar las solicitudes de base de datos",
    ],
    respuestaCorrecta: "Iniciar un servidor para que escuche las solicitudes HTTP en un puerto específico",
    categoria: "Módulo 2: L-07 Express",
    seccion: "03 Creación de servidor",
  },
  {
    id: 14,
    pregunta: "¿Cuál es la utilidad del callback en el método listen de Express?",
    opciones: [
      "Realizar acciones específicas después de que el servidor se ha iniciado correctamente",
      "Definir las rutas de la aplicación web",
      "Realizar operaciones de autenticación de usuarios",
      "Gestionar las solicitudes de base de datos",
    ],
    respuestaCorrecta: "Realizar acciones específicas después de que el servidor se ha iniciado correctamente",
    categoria: "Módulo 2: L-07 Express",
    seccion: "03 Creación de servidor",
  },
  {
    id: 15,
    pregunta: "¿Qué función cumplen los controladores en el contexto de desarrollo web?",
    opciones: [
      "Manejar las solicitudes HTTP, llevando a cabo la lógica necesaria y enviando una respuesta al cliente",
      "Gestionar la interacción con la base de datos",
      "Definir la estructura y el estilo de la página web",
      "Controlar el acceso de los usuarios a las diferentes partes de la aplicación",
    ],
    respuestaCorrecta: "Manejar las solicitudes HTTP, llevando a cabo la lógica necesaria y enviando una respuesta al cliente",
    categoria: "Módulo 2: L-07 Express",
    seccion: "04 Controladores",
  },
  {
    id: 16,
    pregunta: "¿Cuál es el propósito principal del enrutado en Express?",
    opciones: [
      "Gestionar las rutas de la aplicación y dirigir las solicitudes hacia controladores específicos",
      "Definir la estructura y el estilo de la página web",
      "Controlar el acceso de los usuarios a las diferentes partes de la aplicación",
      "Realizar operaciones de autenticación de usuarios",
    ],
    respuestaCorrecta: "Gestionar las rutas de la aplicación y dirigir las solicitudes hacia controladores específicos",
    categoria: "Módulo 2: L-07 Express",
    seccion: "05 Enrutado",
  },
];
