module.exports = [
  {
    id: "K01",
    pregunta: "¿Qué estructura de documento utiliza MongoDB para almacenar datos?",
    opciones: ["Tablas con filas y columnas", "Objetos JavaScript", "Archivos XML", "Documentos tipo JSON"],
    respuestaCorrecta: "Documentos tipo JSON",
    categoria: "L-11 Mongoose",
    seccion: "kahoot",
  },
  {
    id: "K02",
    pregunta: "¿Cuál es la función principal de Express.js en una aplicación de Node.js?",
    opciones: [
      "Garantizar la autenticación segura del usuario",
      "Gestionar interacciones con la base de datos",
      "Realizar análisis de datos complejos",
      "Proporcionar un framework web para construir aplicaciones web y APIS",
    ],
    respuestaCorrecta: "Proporcionar un framework web para construir aplicaciones web y APIS",
    categoria: "L-7 Express",
    seccion: "kahoot",
  },
  {
    id: "K03",
    pregunta: "Que imprime en la consola?",
    codigo: {
      lag: "javascript",
      snippet: "a = [1, 2, 3, 4, 5, 6, 7, 8];\nconsole.log(a.slice(1, 5));",
    },
    opciones: ["Error, faltan los ;", "[1, 2, 3, 4, 5 ]", "[2, 3, 4, 5 ]", "[2, 3, 4, 5, 6 ]"],
    respuestaCorrecta: "[2, 3, 4, 5 ]",
    categoria: "varios",
    seccion: "kahoot",
  },
  {
    id: "K04",
    pregunta: "¿Qué es Docker?",
    opciones: [
      "Una plataforma de virtualización de contenedores",
      "Un framework para desarrollo de aplicaciones web",
      "Un servicio en la nube para el alojamiento de bases de datos",
      "Un sistema operativo completo para el desarrollo de software",
    ],
    respuestaCorrecta: "Una plataforma de virtualización de contenedores",
    categoria: "varios",
    seccion: "kahoot",
  },
  {
    id: "K05",
    categoria: "L-7 Express",
    seccion: "kahoot",
    pregunta: "¿Cuál es el propósito del método populate() de mongoose?",
    opciones: [
      "Para actualizar documentos existentes en una colección",
      "Para eliminar documentos de una colección",
      "Para recuperar documentos de una colección y completar referencias de otras",
      "Para insertar nuevos documentos en una colección",
    ],
    respuestaCorrecta: "Para recuperar documentos de una colección y completar referencias de otras",
  },
  {
    id: "K06",
    categoria: "L-9 Database Fundamentals",
    seccion: "kahoot",
    pregunta: "En una base de datos relacional ¿cuáles son los distintos tipos de relaciones que pueden existir entre tablas?",
    opciones: ["Uno a uno", "Uno a muchos", "Muchos a muchos", "Todas las anteriores"],
    respuestaCorrecta: "Todas las anteriores",
  },
  {
    id: "K7",
    categoria: "varios",
    seccion: "kahoot",
    pregunta: "¿Qué se registra en la consola cuando se llame a innerFunction() Teniendo en cuenta el siguiente fragmento de código:",
    codigo: {
      lag: "javascript",
      snippet:
        'var outerVar = "Valor de la variable global"\nfunction outerFunction() {\n  let outerVar = "variable externa";\n\n  function innerFunction() {\n    console.log(outerVar);\n  }\n\n  return innerFunction;\n}\n\nconst innerFunction = outerFunction();\ninnerFunction(); ',
    },
    opciones: ["Valor de la variable global", "Undefined", "Error de referencia", "Variable externa"],
    respuestaCorrecta: "Variable externa",
  },
  {
    id: "K8",
    categoria: "varios",
    seccion: "kahoot",
    pregunta: "¿Qué propiedad del objeto de solicitud rápida contiene el método HTTP de la request?",
    opciones: ["request.httpMethod", "request.method", "request.reqMethod", "request.HTTPMethod"],
    respuestaCorrecta: "request.method",
  },
  {
    id: "K9",
    categoria: "L-6 Asincronismo",
    seccion: "kahoot",
    pregunta: "¿Cuál es el propósito del bloque 'catch' en una declaración try-catch?",
    opciones: [
      "Definir las condiciones bajo las cuales se debe ejecutar el bloque 'try'",
      "Manejar el error con gracia y evitar la terminación del programa",
      "Para ejecutar código cuando ocurre un error dentro del bloque 'try'",
      "Ejecutar código independientemente de si ocurre uno error o no",
    ],
    respuestaCorrecta: "Manejar el error con gracia y evitar la terminación del programa",
  },
  {
    id: "K10",
    categoria: "L-12 Mongoose II",
    seccion: "kahoot",
    pregunta: "¿Cuál es el propósito de la función next() de Express en el middleware de manejo de errores?",
    opciones: [
      "Para registrar el mensaje de error en la consola",
      "Devolver una respuesta de error al cliente",
      "Dar por terminado el ciclo solicitud-respuesta",
      "Pasar el control al siguiente middleware de la pila",
    ],
    respuestaCorrecta: "Pasar el control al siguiente middleware de la pila",
  },
  {
    id: "K11",
    categoria: "varios",
    seccion: "kahoot",
    pregunta: "¿Cómo se envía una respuesta de error personalizada con status 404 (Not Found)?",
    opciones: ["res.send('Error: Not Found');", "res.status(404).end();", "res.status(404).json({ mensaje:  'No encontrado' });", "Throw new Error('No encontrado');"],
    respuestaCorrecta: "res.status(404).json({ mensaje:  'No encontrado' });",
  },
  {
    id: "K12",
    categoria: "L-6 Asincronismo",
    seccion: "kahoot",
    pregunta: "Con éste código como ejemplo, contestar ¿Qué es document? ",
    opciones: [
      "El documento en sí, con sus propiedades",
      "El objeto global que representa el modelo del documento",
      "Un scope local que representa el modelo del documento en JavaScript",
      "No lo sé Henry, son todas falsas",
    ],
    codigo: {
      lag: "javascript",
      snippet: 'const title = document.getElementById("title").value;',
    },
    respuestaCorrecta: "El objeto global que representa el modelo del documento",
  },
  {
    id: "K13",
    categoria: "L-6 Asincronismo",
    seccion: "kahoot",
    pregunta: "La palabra clave 'await' se utiliza para esperar que una promesa se resuelva en una función asíncrona en JavaScript.",
    opciones: ["Verdadero", "Falso"],
    respuestaCorrecta: "Verdadero",
  },
  {
    id: "K14",
    categoria: "L-6 Asincronismo",
    seccion: "kahoot",
    pregunta: "En una función async, se puede utilizar return para devolver un valor, pero este valor siempre será una promesa resuelta.",
    opciones: ["Verdadero", "Falso"],
    respuestaCorrecta: "Verdadero",
  },
  {
    id: "K15",
    categoria: "L-12 Mongoose II",
    seccion: "kahoot",
    pregunta: "¿Cuál de los siguientes métodos se utiliza para definir un manejador de ruta en Express?",
    opciones: ["app.get('/ruta', function)", "app.get('/ruta').function()", "routeDefine.js", "getURL()"],
    respuestaCorrecta: "app.get('/ruta', function)",
  },
  {
    id: "K16",
    categoria: "varios",
    seccion: "kahoot",
    pregunta: "Las expresiones 'i=i+1' ó 'i++' ó 'i+=1' sirven de igual manera cuando necesitamos un contador.",
    opciones: ["Verdadero", "Falso"],
    respuestaCorrecta: "Verdadero",
  },
  {
    id: "K17",
    categoria: "L-1 Proyecto Full Stack",
    seccion: "kahoot",
    pregunta: "¿Qué es un contexto de ejecución en JavaScript?",
    opciones: [
      "El entorno donde se ejecuta y evalúa el código JavaScript",
      "Una función que se puede llamar varias veces",
      "Una variable global utilizada para almacenar datos",
      "Una forma de definir diferentes alcances para las variables",
    ],
    respuestaCorrecta: "El entorno donde se ejecuta y evalúa el código JavaScript",
  },
  {
    id: "K18",
    categoria: "varios",
    seccion: "kahoot",
    pregunta: 'Si utilizamos el método Math.floor() con el valor "-5.1" devuelve -5.',
    opciones: ["Verdadero", "Falso"],
    respuestaCorrecta: "Falso",
  },
];

// "id": "K05",
// "categoria": "varios",
// "seccion": "kahoot",
